---
- name: Prepare venv and install openstacksdk
  hosts: src_cloud
  vars_files:
    - src-vars.yml
  tasks:
    - name: Ensure python3-venv and pip are installed
      apt:
        name:
          - python3-venv
          - python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Create Python virtual environment if not exists
      command: "python3 -m venv {{ venv_path }}"
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Ensure openstacksdk is installed in virtualenv
      ansible.builtin.pip:
        name: openstacksdk
        virtualenv: "{{ venv_path }}"
        virtualenv_command: python3 -m venv

- name: List servers
  hosts: src_cloud
  vars_files:
    - src-vars.yml
  tasks:
    - name: List servers
      openstack.cloud.server_info:
        auth: "{{ cloud_config.auth }}"
      register: servers_list
    
    - name: Show server list
      set_stats:
        data:
          servers: "{{ servers_list }}"